version: '3.8'

volumes:
  foodgram_db:
  static_value:
  media_value:

services:
  db:
    image: postgres:14-alpine
    volumes:
      - foodgram_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend/
    image: egrivtsov/foodgram:latest
    restart: always
    volumes:
        - static_value:/app/static/
        - media_value:/app/media/
    depends_on:
        - db
    env_file:
        - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

