# Generated by Django 4.2.1 on 2023-05-11 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={
                "default_related_name": "tags",
                "ordering": ("id",),
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
    ]
