# Generated by Django 4.2.1 on 2023-05-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_tags_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="tags",
            field=models.ManyToManyField(
                related_name="tags", to="recipes.tags"
            ),
        ),
    ]
