# Generated by Django 4.2.1 on 2023-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                help_text="Придумайте пароль \n            (не более 150 символов)",
                max_length=150,
                verbose_name="Пароль",
            ),
        ),
    ]
