# Generated by Django 4.2.1 on 2023-05-19 11:25

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "Пользователь с таким электронным почтовым адресом уже существует."
                },
                help_text="Введите электронный почтовый адрес\n            (не более 254 символов)",
                max_length=254,
                unique=True,
                verbose_name="Электронный почтовый адрес",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                help_text="Введите имя пользователя\n            (не более 150 символов)",
                max_length=150,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                help_text="Введите фамилию пользователя\n            (не более 150 символов)",
                max_length=150,
                verbose_name="Фамилия пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                help_text="Придумайте пароль\n            (не более 150 символов)",
                max_length=150,
                verbose_name="Пароль",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "Пользователь с таким именем уже существует!"
                },
                help_text="Введите юзернейм пользователя\n            (не более 150 символов)",
                max_length=150,
                unique=True,
                validators=[
                    users.validators.username_pattern_validation,
                    users.validators.username_name_list_validator,
                ],
                verbose_name="Юзернейм",
            ),
        ),
    ]
