# Generated by Django 4.2.1 on 2023-05-16 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ("-id",),
                "verbose_name": "Подписка на автора",
                "verbose_name_plural": "Подписки на авторов",
            },
        ),
    ]
